package layer3

import (
	"github.com/PaloAltoNetworks/pango/version"
)

type testCase struct {
	version    version.Number
	tmpl       string
	vsys       string
	importVsys string
	imports    []string
	conf       Entry
}

func getTests() []testCase {
	return []testCase{
		{version.Number{7, 1, 0, ""}, "tmpl1", "vsys1", "vsys1", []string{"ethernet1/1.2"}, Entry{
			Name:              "ethernet1/1.2",
			Tag:               2,
			StaticIps:         []string{"10.1.1.1/24", "10.2.1.1/24"},
			Ipv6Enabled:       true,
			ManagementProfile: "enable ping",
			Mtu:               1500,
			AdjustTcpMss:      true,
			Ipv4MssAdjust:     5,
			Ipv6MssAdjust:     6,
			NetflowProfile:    "some profile",
			Comment:           "v1 basic",
		}},
		{version.Number{7, 1, 0, ""}, "tmpl2", "vsys1", "vsys1", []string{"ethernet1/1.3"}, Entry{
			Name:                   "ethernet1/1.3",
			Tag:                    3,
			ManagementProfile:      "enable ping",
			Mtu:                    1600,
			EnableDhcp:             true,
			DhcpDefaultRouteMetric: 5,
			NetflowProfile:         "some profile",
			Comment:                "v1 dhcp without default route",
		}},
		{version.Number{7, 1, 0, ""}, "tmpl3", "vsys1", "vsys1", []string{"ethernet1/1.4"}, Entry{
			Name:                   "ethernet1/1.4",
			Tag:                    4,
			ManagementProfile:      "enable ping",
			Mtu:                    1600,
			EnableDhcp:             true,
			CreateDhcpDefaultRoute: true,
			DhcpDefaultRouteMetric: 5,
			NetflowProfile:         "some profile",
			Comment:                "v1 dhcp with default route",
		}},
		{version.Number{7, 1, 0, ""}, "tmpl4", "vsys1", "vsys1", []string{"ethernet1/1.5"}, Entry{
			Name:                   "ethernet1/1.5",
			Tag:                    5,
			Ipv6Enabled:            true,
			Ipv6InterfaceId:        "v6-interface-id",
			ManagementProfile:      "block everything",
			Mtu:                    2600,
			EnableDhcp:             true,
			CreateDhcpDefaultRoute: true,
			Comment:                "v1 dhcp with raw",
			raw: map[string]string{
				"arp":   "arp entries",
				"ndp":   "ndp info",
				"v6adr": "ipv6 addresses",
				"v6nbr": "ipv6 neighbor info",
			},
		}},
		{version.Number{8, 1, 0, ""}, "tmpl5", "vsys1", "vsys1", []string{"ethernet1/1.2"}, Entry{
			Name:              "ethernet1/1.2",
			Tag:               2,
			StaticIps:         []string{"10.1.1.1/24", "10.2.1.1/24"},
			Ipv6Enabled:       true,
			ManagementProfile: "enable ping",
			Mtu:               1500,
			AdjustTcpMss:      true,
			Ipv4MssAdjust:     5,
			Ipv6MssAdjust:     6,
			NetflowProfile:    "some profile",
			Comment:           "v1 basic",
		}},
		{version.Number{8, 1, 0, ""}, "tmpl6", "vsys1", "vsys1", []string{"ethernet1/1.3"}, Entry{
			Name:                   "ethernet1/1.3",
			Tag:                    3,
			ManagementProfile:      "enable ping",
			Mtu:                    1600,
			EnableDhcp:             true,
			DhcpDefaultRouteMetric: 5,
			NetflowProfile:         "some profile",
			Comment:                "v1 dhcp without default route",
		}},
		{version.Number{8, 1, 0, ""}, "tmpl7", "vsys1", "vsys1", []string{"ethernet1/1.4"}, Entry{
			Name:                   "ethernet1/1.4",
			Tag:                    4,
			ManagementProfile:      "enable ping",
			Mtu:                    1600,
			EnableDhcp:             true,
			CreateDhcpDefaultRoute: true,
			DhcpDefaultRouteMetric: 5,
			NetflowProfile:         "some profile",
			Comment:                "v1 dhcp with default route",
		}},
		{version.Number{8, 1, 0, ""}, "tmpl8", "vsys1", "vsys1", []string{"ethernet1/1.5"}, Entry{
			Name:                   "ethernet1/1.5",
			Tag:                    5,
			DecryptForward:         true,
			Ipv6Enabled:            true,
			Ipv6InterfaceId:        "v6-interface-id",
			ManagementProfile:      "block everything",
			Mtu:                    2600,
			EnableDhcp:             true,
			CreateDhcpDefaultRoute: true,
			Comment:                "v1 dhcp with raw and decrypt forward",
			raw: map[string]string{
				"arp":   "arp entries",
				"ndp":   "ndp info",
				"v6adr": "ipv6 addresses",
				"v6nbr": "ipv6 neighbor info",
			},
		}},
		{version.Number{9, 0, 0, ""}, "tmpl9", "vsys1", "vsys1", []string{"ethernet1/1.2"}, Entry{
			Name:              "ethernet1/1.2",
			Tag:               2,
			StaticIps:         []string{"10.1.1.1/24", "10.2.1.1/24"},
			Ipv6Enabled:       true,
			ManagementProfile: "enable ping",
			Mtu:               1500,
			AdjustTcpMss:      true,
			Ipv4MssAdjust:     5,
			Ipv6MssAdjust:     6,
			NetflowProfile:    "some profile",
			Comment:           "v1 basic",
		}},
		{version.Number{9, 0, 0, ""}, "tmpl10", "vsys1", "vsys1", []string{"ethernet1/1.3"}, Entry{
			Name:                   "ethernet1/1.3",
			Tag:                    3,
			ManagementProfile:      "enable ping",
			Mtu:                    1600,
			EnableDhcp:             true,
			DhcpDefaultRouteMetric: 5,
			NetflowProfile:         "some profile",
			Comment:                "v1 dhcp without default route",
		}},
		{version.Number{9, 0, 0, ""}, "tmpl11", "vsys1", "vsys1", []string{"ethernet1/1.4"}, Entry{
			Name:                   "ethernet1/1.4",
			Tag:                    4,
			ManagementProfile:      "enable ping",
			Mtu:                    1600,
			EnableDhcp:             true,
			CreateDhcpDefaultRoute: true,
			DhcpDefaultRouteMetric: 5,
			NetflowProfile:         "some profile",
			Comment:                "v1 dhcp with default route",
		}},
		{version.Number{9, 0, 0, ""}, "tmpl12", "vsys1", "vsys1", []string{"ethernet1/1.5"}, Entry{
			Name:                   "ethernet1/1.5",
			Tag:                    5,
			DecryptForward:         true,
			Ipv6Enabled:            true,
			Ipv6InterfaceId:        "v6-interface-id",
			ManagementProfile:      "block everything",
			Mtu:                    2600,
			EnableDhcp:             true,
			CreateDhcpDefaultRoute: true,
			Comment:                "v1 dhcp with raw and decrypt forward",
			raw: map[string]string{
				"arp":   "arp entries",
				"ndp":   "ndp info",
				"v6adr": "ipv6 addresses",
				"v6nbr": "ipv6 neighbor info",
			},
		}},
		{version.Number{9, 0, 0, ""}, "tmpl13", "vsys1", "vsys1", []string{"ethernet1/1.6"}, Entry{
			Name:                   "ethernet1/1.6",
			Tag:                    6,
			ManagementProfile:      "allow ssh",
			Mtu:                    1100,
			EnableDhcp:             true,
			DhcpSendHostnameEnable: true,
			DhcpSendHostnameValue:  "foo.bar.com",
			NetflowProfile:         "some profile",
			Comment:                "v1 dhcp with send hostname",
		}},
	}
}
