package certificate

import (
	"github.com/PaloAltoNetworks/pango/version"
)

type tc struct {
	desc    string
	version version.Number
	conf    Entry
}

func getTests() []tc {
	return []tc{
		{"v1 none username with usecrl", version.Number{6, 1, 0, ""}, Entry{
			Name:                     "myCert",
			Domain:                   "example.com",
			UseCrl:                   true,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  false,
		}},
		{"v1 subject username with useocsp", version.Number{6, 1, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubject,
			UsernameFieldValue:       UsernameFieldValueCommonName,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  true,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  false,
		}},
		{"v1 email alt-subject with block unknown cert", version.Number{6, 1, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubjectAlt,
			UsernameFieldValue:       UsernameFieldValueEmail,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  true,
			BlockCertificateTimeout:  false,
		}},
		{"v1 principal name alt-subject with block cert timeout", version.Number{6, 1, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubjectAlt,
			UsernameFieldValue:       UsernameFieldValuePrincipalName,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  true,
		}},
		{"v1 with certs", version.Number{6, 1, 0, ""}, Entry{
			Name:   "myCert",
			Domain: "example.com",
			Certificates: []Certificate{
				{
					Name:                  "c1",
					DefaultOcspUrl:        "myOcspUrl",
					OcspVerifyCertificate: "foobar",
				},
			},
			CrlReceiveTimeout:        6,
			OcspReceiveTimeout:       4,
			CertificateStatusTimeout: 2,
		}},
		{"v2 none username with usecrl", version.Number{7, 1, 0, ""}, Entry{
			Name:                     "myCert",
			Domain:                   "example.com",
			UseCrl:                   true,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  false,
		}},
		{"v2 subject username with useocsp", version.Number{7, 1, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubject,
			UsernameFieldValue:       UsernameFieldValueCommonName,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  true,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  false,
		}},
		{"v2 email alt-subject with block unknown cert", version.Number{7, 1, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubjectAlt,
			UsernameFieldValue:       UsernameFieldValueEmail,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  true,
			BlockCertificateTimeout:  false,
		}},
		{"v2 principal name alt-subject with block cert timeout", version.Number{7, 1, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubjectAlt,
			UsernameFieldValue:       UsernameFieldValuePrincipalName,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  true,
		}},
		{"v2 with certs", version.Number{7, 1, 0, ""}, Entry{
			Name:   "myCert",
			Domain: "example.com",
			Certificates: []Certificate{
				{
					Name:                  "c1",
					DefaultOcspUrl:        "myOcspUrl",
					OcspVerifyCertificate: "foobar",
				},
			},
			CrlReceiveTimeout:        6,
			OcspReceiveTimeout:       4,
			CertificateStatusTimeout: 2,
		}},
		{"v2 none username with block unauthenticated certificate", version.Number{7, 1, 0, ""}, Entry{
			Name:                            "myCert",
			Domain:                          "example.com",
			CrlReceiveTimeout:               1,
			OcspReceiveTimeout:              2,
			CertificateStatusTimeout:        3,
			BlockUnauthenticatedCertificate: true,
		}},
		{"v3 none username with usecrl", version.Number{8, 1, 0, ""}, Entry{
			Name:                     "myCert",
			Domain:                   "example.com",
			UseCrl:                   true,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  false,
		}},
		{"v3 subject username with useocsp", version.Number{8, 1, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubject,
			UsernameFieldValue:       UsernameFieldValueCommonName,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  true,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  false,
		}},
		{"v3 email alt-subject with block unknown cert", version.Number{8, 1, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubjectAlt,
			UsernameFieldValue:       UsernameFieldValueEmail,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  true,
			BlockCertificateTimeout:  false,
		}},
		{"v3 principal name alt-subject with block cert timeout", version.Number{8, 1, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubjectAlt,
			UsernameFieldValue:       UsernameFieldValuePrincipalName,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  true,
		}},
		{"v3 with certs", version.Number{8, 1, 0, ""}, Entry{
			Name:   "myCert",
			Domain: "example.com",
			Certificates: []Certificate{
				{
					Name:                  "c1",
					DefaultOcspUrl:        "myOcspUrl",
					OcspVerifyCertificate: "foobar",
				},
			},
			CrlReceiveTimeout:        6,
			OcspReceiveTimeout:       4,
			CertificateStatusTimeout: 2,
		}},
		{"v3 none username with block unauthenticated certificate", version.Number{8, 1, 0, ""}, Entry{
			Name:                            "myCert",
			Domain:                          "example.com",
			CrlReceiveTimeout:               1,
			OcspReceiveTimeout:              2,
			CertificateStatusTimeout:        3,
			BlockUnauthenticatedCertificate: true,
		}},
		{"v3 none username with block expired certificate", version.Number{8, 1, 0, ""}, Entry{
			Name:                     "myCert",
			Domain:                   "example.com",
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockExpiredCertificate:  true,
		}},
		{"v4 none username with usecrl", version.Number{9, 0, 0, ""}, Entry{
			Name:                     "myCert",
			Domain:                   "example.com",
			UseCrl:                   true,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  false,
		}},
		{"v4 subject username with useocsp", version.Number{9, 0, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubject,
			UsernameFieldValue:       UsernameFieldValueCommonName,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  true,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  false,
		}},
		{"v4 email alt-subject with block unknown cert", version.Number{9, 0, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubjectAlt,
			UsernameFieldValue:       UsernameFieldValueEmail,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  true,
			BlockCertificateTimeout:  false,
		}},
		{"v4 principal name alt-subject with block cert timeout", version.Number{9, 0, 0, ""}, Entry{
			Name:                     "myCert",
			UsernameField:            UsernameFieldSubjectAlt,
			UsernameFieldValue:       UsernameFieldValuePrincipalName,
			Domain:                   "example.com",
			UseCrl:                   false,
			UseOcsp:                  false,
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockUnknownCertificate:  false,
			BlockCertificateTimeout:  true,
		}},
		{"v4 with certs", version.Number{9, 0, 0, ""}, Entry{
			Name:   "myCert",
			Domain: "example.com",
			Certificates: []Certificate{
				{
					Name:                  "c1",
					DefaultOcspUrl:        "myOcspUrl",
					OcspVerifyCertificate: "foobar",
				},
			},
			CrlReceiveTimeout:        6,
			OcspReceiveTimeout:       4,
			CertificateStatusTimeout: 2,
		}},
		{"v4 none username with block unauthenticated certificate", version.Number{9, 0, 0, ""}, Entry{
			Name:                            "myCert",
			Domain:                          "example.com",
			CrlReceiveTimeout:               1,
			OcspReceiveTimeout:              2,
			CertificateStatusTimeout:        3,
			BlockUnauthenticatedCertificate: true,
		}},
		{"v4 none username with block expired certificate", version.Number{9, 0, 0, ""}, Entry{
			Name:                     "myCert",
			Domain:                   "example.com",
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			BlockExpiredCertificate:  true,
		}},
		{"v4 with template name cert", version.Number{9, 0, 0, ""}, Entry{
			Name:   "myCert",
			Domain: "example.com",
			Certificates: []Certificate{
				{
					Name:                  "c1",
					DefaultOcspUrl:        "myOcspUrl",
					OcspVerifyCertificate: "foobar",
					TemplateName:          "templateName",
				},
			},
			CrlReceiveTimeout:        6,
			OcspReceiveTimeout:       4,
			CertificateStatusTimeout: 2,
		}},
		{"v4 none username with ocsp exclude nonce", version.Number{9, 0, 0, ""}, Entry{
			Name:                     "myCert",
			Domain:                   "example.com",
			CrlReceiveTimeout:        1,
			OcspReceiveTimeout:       2,
			CertificateStatusTimeout: 3,
			OcspExcludeNonce:         true,
		}},
	}
}
