package security

import (
	"github.com/PaloAltoNetworks/pango/util"
	"github.com/PaloAltoNetworks/pango/version"
)

type testCase struct {
	version version.Number
	desc    string
	vsys    string
	base    string
	conf    Entry
}

func getTests() []testCase {
	return []testCase{
		{version.Number{6, 1, 0, ""}, "basic rule", "", "", Entry{
			Name:                 "rule1",
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               false,
		}},
		{version.Number{6, 1, 0, ""}, "prerulebase rule", "vsys2", util.PreRulebase, Entry{
			Name:                 "rule2",
			Disabled:             true,
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               true,
		}},
		{version.Number{6, 1, 0, ""}, "postrulebase rule with target", "vsys3", util.PostRulebase, Entry{
			Name: "rule3",
			Targets: map[string][]string{
				"fw1": nil,
				"fw2": {"vsys2", "vsys3"},
			},
			NegateTarget:         true,
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               false,
		}},
		{version.Number{9, 0, 0, ""}, "basic rule", "", "", Entry{
			Name:                 "rule1",
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               false,
		}},
		{version.Number{9, 0, 0, ""}, "rule with uuid", "", "", Entry{
			Name:                 "rule1",
			Uuid:                 "123-456-78",
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               true,
		}},
		{version.Number{9, 0, 0, ""}, "prerulebase rule", "vsys2", util.PreRulebase, Entry{
			Name:                 "rule2",
			Disabled:             true,
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               false,
		}},
		{version.Number{9, 0, 0, ""}, "postrulebase rule with target", "vsys3", util.PostRulebase, Entry{
			Name: "rule3",
			Targets: map[string][]string{
				"fw1": nil,
				"fw2": {"vsys2", "vsys3"},
			},
			NegateTarget:         true,
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               true,
		}},
		{version.Number{9, 0, 0, ""}, "rule with group tag", "", "", Entry{
			Name:                 "rule1",
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               false,
			GroupTag:             "oneTime",
		}},
		{version.Number{10, 0, 0, ""}, "basic rule", "", "", Entry{
			Name:                 "rule1",
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               false,
		}},
		{version.Number{10, 0, 0, ""}, "rule with uuid", "", "", Entry{
			Name:                 "rule1",
			Uuid:                 "123-456-78",
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               true,
		}},
		{version.Number{10, 0, 0, ""}, "rule with source and dest devices", "", "", Entry{
			Name:                 "rule1",
			SourceDevices:        []string{"src1", "wu tang"},
			DestinationDevices:   []string{"dest1", "clan"},
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               false,
		}},
		{version.Number{10, 0, 0, ""}, "prerulebase rule", "vsys2", util.PreRulebase, Entry{
			Name:                 "rule2",
			Disabled:             true,
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               true,
		}},
		{version.Number{10, 0, 0, ""}, "postrulebase rule with target", "vsys3", util.PostRulebase, Entry{
			Name: "rule3",
			Targets: map[string][]string{
				"fw1": nil,
				"fw2": {"vsys2", "vsys3"},
			},
			NegateTarget:         true,
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               false,
		}},
		{version.Number{10, 0, 0, ""}, "rule with group tag", "", "", Entry{
			Name:                 "rule1",
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               true,
			GroupTag:             "oneTime",
		}},
		{version.Number{10, 0, 0, ""}, "rule with source and dst devices", "", "", Entry{
			Name:                 "rule1",
			Type:                 "universal",
			SourceZones:          []string{"sz1", "sz2"},
			SourceAddresses:      []string{"sa1", "sa2"},
			SourceUsers:          []string{"su1", "su2"},
			HipProfiles:          []string{"hp3", "hp2", "hp1"},
			DestinationZones:     []string{"dz1", "dz2"},
			DestinationAddresses: []string{"da1", "da2"},
			Applications:         []string{"app1"},
			Services:             []string{"s2", "s1"},
			Categories:           []string{"cat1"},
			Action:               "allow",
			LogEnd:               true,
			SourceDevices:        []string{"src2", "src1"},
			DestinationDevices:   []string{"dstDev"},
		}},
	}
}
