package edl

import (
	"github.com/PaloAltoNetworks/pango/version"
)

type testCase struct {
	desc    string
	version version.Number
	conf    Entry
}

func getTests() []testCase {
	return []testCase{
		{"v1 ip hourly", version.Number{6, 1, 0, ""}, Entry{
			Name:        "one",
			Type:        TypeIp,
			Description: "first",
			Source:      "http://1.1.1.1",
			Repeat:      RepeatHourly,
		}},
		{"v1 domain daily", version.Number{6, 1, 0, ""}, Entry{
			Name:        "three",
			Type:        TypeDomain,
			Description: "third",
			Source:      "http://3.3.3.3",
			Repeat:      RepeatDaily,
			RepeatAt:    "12:34",
		}},
		{"v1 url weekly", version.Number{6, 1, 0, ""}, Entry{
			Name:            "four",
			Type:            TypeUrl,
			Description:     "fourth",
			Source:          "http://4.4.4.4",
			Repeat:          RepeatWeekly,
			RepeatAt:        "actually invalid",
			RepeatDayOfWeek: "tuesday",
		}},
		{"v1 url monthly", version.Number{6, 1, 0, ""}, Entry{
			Name:             "five",
			Type:             TypeUrl,
			Description:      "fifth",
			Source:           "http://5.5.5.5",
			Repeat:           RepeatMonthly,
			RepeatAt:         "also invalid",
			RepeatDayOfMonth: 7,
		}},
		{"v2 ip hourly", version.Number{8, 0, 0, ""}, Entry{
			Name:        "one",
			Type:        TypeIp,
			Description: "first",
			Source:      "http://1.1.1.1",
			Repeat:      RepeatHourly,
		}},
		{"v2 domain daily", version.Number{8, 0, 0, ""}, Entry{
			Name:        "three",
			Type:        TypeDomain,
			Description: "third",
			Source:      "http://3.3.3.3",
			Repeat:      RepeatDaily,
			RepeatAt:    "12:34",
		}},
		{"v2 url weekly", version.Number{8, 0, 0, ""}, Entry{
			Name:            "four",
			Type:            TypeUrl,
			Description:     "fourth",
			Source:          "http://4.4.4.4",
			Repeat:          RepeatWeekly,
			RepeatAt:        "actually invalid",
			RepeatDayOfWeek: "tuesday",
		}},
		{"v2 url monthly", version.Number{8, 0, 0, ""}, Entry{
			Name:             "five",
			Type:             TypeUrl,
			Description:      "fifth",
			Source:           "http://5.5.5.5",
			Repeat:           RepeatMonthly,
			RepeatAt:         "also invalid",
			RepeatDayOfMonth: 7,
		}},
		{"v2 predefined", version.Number{8, 0, 0, ""}, Entry{
			Name:        "six",
			Type:        TypePredefinedIp,
			Description: "predef test",
			Source:      "http://7.7.7.7:8444",
			Exceptions:  []string{"ex1", "ex2"},
		}},
		{"v2 ip with cert and auth", version.Number{8, 0, 0, ""}, Entry{
			Name:               "seven",
			Type:               TypeIp,
			Description:        "ip with cert and auth",
			Source:             "https://8.8.8.8",
			CertificateProfile: "myProfile",
			Username:           "admin",
			Password:           "swordfish",
			Exceptions:         []string{"firstException", "secondOne"},
		}},
		{"v3 ip hourly", version.Number{9, 0, 0, ""}, Entry{
			Name:        "one",
			Type:        TypeIp,
			Description: "first",
			Source:      "http://1.1.1.1",
			Repeat:      RepeatHourly,
		}},
		{"v3 domain daily", version.Number{9, 0, 0, ""}, Entry{
			Name:        "three",
			Type:        TypeDomain,
			Description: "third",
			Source:      "http://3.3.3.3",
			Repeat:      RepeatDaily,
			RepeatAt:    "12:34",
		}},
		{"v3 url weekly", version.Number{9, 0, 0, ""}, Entry{
			Name:            "four",
			Type:            TypeUrl,
			Description:     "fourth",
			Source:          "http://4.4.4.4",
			Repeat:          RepeatWeekly,
			RepeatAt:        "actually invalid",
			RepeatDayOfWeek: "tuesday",
		}},
		{"v3 url monthly", version.Number{9, 0, 0, ""}, Entry{
			Name:             "five",
			Type:             TypeUrl,
			Description:      "fifth",
			Source:           "http://5.5.5.5",
			Repeat:           RepeatMonthly,
			RepeatAt:         "also invalid",
			RepeatDayOfMonth: 7,
		}},
		{"v3 predefined", version.Number{9, 0, 0, ""}, Entry{
			Name:        "six",
			Type:        TypePredefinedIp,
			Description: "predef test",
			Source:      "http://7.7.7.7:8444",
			Exceptions:  []string{"ex1", "ex2"},
		}},
		{"v3 ip with cert and auth", version.Number{9, 0, 0, ""}, Entry{
			Name:               "seven",
			Type:               TypeIp,
			Description:        "ip with cert and auth",
			Source:             "https://8.8.8.8",
			CertificateProfile: "myProfile",
			Username:           "admin",
			Password:           "swordfish",
			Exceptions:         []string{"firstException", "secondOne"},
		}},
		{"v3 domain with expand domain", version.Number{9, 0, 0, ""}, Entry{
			Name:         "eight",
			Type:         TypeDomain,
			Description:  "domain with expand domain",
			Source:       "https://localhost",
			ExpandDomain: true,
			Username:     "foo",
			Password:     "bar",
			Exceptions:   []string{"example.com"},
		}},
		{"v4 ip hourly", version.Number{10, 0, 0, ""}, Entry{
			Name:        "one",
			Type:        TypeIp,
			Description: "first",
			Source:      "http://1.1.1.1",
			Repeat:      RepeatHourly,
		}},
		{"v4 domain daily", version.Number{10, 0, 0, ""}, Entry{
			Name:        "three",
			Type:        TypeDomain,
			Description: "third",
			Source:      "http://3.3.3.3",
			Repeat:      RepeatDaily,
			RepeatAt:    "12:34",
		}},
		{"v4 url weekly", version.Number{10, 0, 0, ""}, Entry{
			Name:            "four",
			Type:            TypeUrl,
			Description:     "fourth",
			Source:          "http://4.4.4.4",
			Repeat:          RepeatWeekly,
			RepeatAt:        "actually invalid",
			RepeatDayOfWeek: "tuesday",
		}},
		{"v4 url monthly", version.Number{10, 0, 0, ""}, Entry{
			Name:             "five",
			Type:             TypeUrl,
			Description:      "fifth",
			Source:           "http://5.5.5.5",
			Repeat:           RepeatMonthly,
			RepeatAt:         "also invalid",
			RepeatDayOfMonth: 7,
		}},
		{"v4 predefined", version.Number{10, 0, 0, ""}, Entry{
			Name:        "six",
			Type:        TypePredefinedIp,
			Description: "predef test",
			Source:      "http://7.7.7.7:8444",
			Exceptions:  []string{"ex1", "ex2"},
		}},
		{"v4 ip with cert and auth", version.Number{10, 0, 0, ""}, Entry{
			Name:               "seven",
			Type:               TypeIp,
			Description:        "ip with cert and auth",
			Source:             "https://8.8.8.8",
			CertificateProfile: "myProfile",
			Username:           "admin",
			Password:           "swordfish",
			Exceptions:         []string{"firstException", "secondOne"},
		}},
		{"v4 domain with expand domain", version.Number{10, 0, 0, ""}, Entry{
			Name:         "eight",
			Type:         TypeDomain,
			Description:  "domain with expand domain",
			Source:       "https://localhost",
			ExpandDomain: true,
			Username:     "foo",
			Password:     "bar",
			Exceptions:   []string{"example.com"},
		}},
		{"v4 predefined url", version.Number{10, 0, 0, ""}, Entry{
			Name:        "nine",
			Type:        TypePredefinedUrl,
			Description: "predef url",
			Source:      "https://127.0.0.1:8443",
			Exceptions:  []string{"palo.com", "alto.com"},
		}},
	}
}
