package bgp

import (
	"github.com/PaloAltoNetworks/pango/version"
)

type testCase struct {
	desc    string
	version version.Number
	conf    Config
}

func getTests() []testCase {
	return []testCase{
		{"v1 bgp no raw", version.Number{6, 1, 0, ""}, Config{
			Enable:                        true,
			RouterId:                      "router id",
			AsNumber:                      "as number",
			RejectDefaultRoute:            false,
			InstallRoute:                  true,
			AggregateMed:                  false,
			DefaultLocalPreference:        "def local pref",
			AsFormat:                      AsFormat2Byte,
			AlwaysCompareMed:              true,
			DeterministicMedComparison:    false,
			EnableGracefulRestart:         true,
			StaleRouteTime:                2,
			LocalRestartTime:              3,
			MaxPeerRestartTime:            4,
			ReflectorClusterId:            "reflector cluster id",
			ConfederationMemberAs:         "conf mem as",
			AllowRedistributeDefaultRoute: false,
		}},
		{"v1 bgp with raw", version.Number{6, 1, 0, ""}, Config{
			Enable:                        true,
			RouterId:                      "router id",
			AsNumber:                      "as number",
			RejectDefaultRoute:            false,
			InstallRoute:                  true,
			AggregateMed:                  false,
			DefaultLocalPreference:        "def local pref",
			AsFormat:                      AsFormat4Byte,
			AlwaysCompareMed:              true,
			DeterministicMedComparison:    false,
			EnableGracefulRestart:         true,
			StaleRouteTime:                2,
			LocalRestartTime:              3,
			MaxPeerRestartTime:            4,
			ReflectorClusterId:            "reflector cluster id",
			ConfederationMemberAs:         "conf mem as",
			AllowRedistributeDefaultRoute: false,
			raw: map[string]string{
				"orf":  "outbound route filter",
				"ap":   "auth profile",
				"dp":   "dampening profile",
				"pg":   "peer group",
				"poli": "policy",
				"rr":   "redist rules",
			},
		}},
		{"v2 bgp no raw", version.Number{7, 0, 0, ""}, Config{
			Enable:                        true,
			RouterId:                      "router id",
			AsNumber:                      "as number",
			RejectDefaultRoute:            false,
			InstallRoute:                  true,
			AggregateMed:                  false,
			DefaultLocalPreference:        "def local pref",
			AsFormat:                      AsFormat2Byte,
			AlwaysCompareMed:              true,
			DeterministicMedComparison:    false,
			EcmpMultiAs:                   true,
			EnableGracefulRestart:         true,
			StaleRouteTime:                2,
			LocalRestartTime:              3,
			MaxPeerRestartTime:            4,
			ReflectorClusterId:            "reflector cluster id",
			ConfederationMemberAs:         "conf mem as",
			AllowRedistributeDefaultRoute: false,
		}},
		{"v2 bgp with raw", version.Number{7, 0, 0, ""}, Config{
			Enable:                        true,
			RouterId:                      "router id",
			AsNumber:                      "as number",
			RejectDefaultRoute:            false,
			InstallRoute:                  true,
			AggregateMed:                  false,
			DefaultLocalPreference:        "def local pref",
			AsFormat:                      AsFormat4Byte,
			AlwaysCompareMed:              true,
			DeterministicMedComparison:    false,
			EcmpMultiAs:                   true,
			EnableGracefulRestart:         true,
			StaleRouteTime:                2,
			LocalRestartTime:              3,
			MaxPeerRestartTime:            4,
			ReflectorClusterId:            "reflector cluster id",
			ConfederationMemberAs:         "conf mem as",
			AllowRedistributeDefaultRoute: false,
			raw: map[string]string{
				"orf":  "outbound route filter",
				"ap":   "auth profile",
				"dp":   "dampening profile",
				"pg":   "peer group",
				"poli": "policy",
				"rr":   "redist rules",
			},
		}},
		{"v3 bgp no raw", version.Number{7, 1, 0, ""}, Config{
			Enable:                        true,
			RouterId:                      "router id",
			AsNumber:                      "as number",
			BfdProfile:                    "None",
			RejectDefaultRoute:            false,
			InstallRoute:                  true,
			AggregateMed:                  false,
			DefaultLocalPreference:        "def local pref",
			AsFormat:                      AsFormat2Byte,
			AlwaysCompareMed:              true,
			DeterministicMedComparison:    false,
			EcmpMultiAs:                   true,
			EnableGracefulRestart:         true,
			StaleRouteTime:                2,
			LocalRestartTime:              3,
			MaxPeerRestartTime:            4,
			ReflectorClusterId:            "reflector cluster id",
			ConfederationMemberAs:         "conf mem as",
			AllowRedistributeDefaultRoute: false,
		}},
		{"v3 bgp with raw", version.Number{7, 1, 0, ""}, Config{
			Enable:                        true,
			RouterId:                      "router id",
			AsNumber:                      "as number",
			BfdProfile:                    "bfd profile",
			RejectDefaultRoute:            false,
			InstallRoute:                  true,
			AggregateMed:                  false,
			DefaultLocalPreference:        "def local pref",
			AsFormat:                      AsFormat4Byte,
			AlwaysCompareMed:              true,
			DeterministicMedComparison:    false,
			EcmpMultiAs:                   true,
			EnableGracefulRestart:         true,
			StaleRouteTime:                2,
			LocalRestartTime:              3,
			MaxPeerRestartTime:            4,
			ReflectorClusterId:            "reflector cluster id",
			ConfederationMemberAs:         "conf mem as",
			AllowRedistributeDefaultRoute: false,
			raw: map[string]string{
				"orf":  "outbound route filter",
				"ap":   "auth profile",
				"dp":   "dampening profile",
				"pg":   "peer group",
				"poli": "policy",
				"rr":   "redist rules",
			},
		}},
		{"v4 bgp no raw", version.Number{8, 0, 0, ""}, Config{
			Enable:                        true,
			RouterId:                      "router id",
			AsNumber:                      "as number",
			BfdProfile:                    "None",
			RejectDefaultRoute:            false,
			InstallRoute:                  true,
			AggregateMed:                  false,
			DefaultLocalPreference:        "def local pref",
			AsFormat:                      AsFormat2Byte,
			AlwaysCompareMed:              true,
			DeterministicMedComparison:    false,
			EcmpMultiAs:                   true,
			EnforceFirstAs:                true,
			EnableGracefulRestart:         true,
			StaleRouteTime:                2,
			LocalRestartTime:              3,
			MaxPeerRestartTime:            4,
			ReflectorClusterId:            "reflector cluster id",
			ConfederationMemberAs:         "conf mem as",
			AllowRedistributeDefaultRoute: false,
		}},
		{"v4 bgp with raw", version.Number{8, 0, 0, ""}, Config{
			Enable:                        true,
			RouterId:                      "router id",
			AsNumber:                      "as number",
			BfdProfile:                    "bfd profile",
			RejectDefaultRoute:            false,
			InstallRoute:                  true,
			AggregateMed:                  false,
			DefaultLocalPreference:        "def local pref",
			AsFormat:                      AsFormat4Byte,
			AlwaysCompareMed:              true,
			DeterministicMedComparison:    false,
			EcmpMultiAs:                   true,
			EnforceFirstAs:                false,
			EnableGracefulRestart:         true,
			StaleRouteTime:                2,
			LocalRestartTime:              3,
			MaxPeerRestartTime:            4,
			ReflectorClusterId:            "reflector cluster id",
			ConfederationMemberAs:         "conf mem as",
			AllowRedistributeDefaultRoute: false,
			raw: map[string]string{
				"orf":  "outbound route filter",
				"ap":   "auth profile",
				"dp":   "dampening profile",
				"pg":   "peer group",
				"poli": "policy",
				"rr":   "redist rules",
			},
		}},
	}
}
