package decryption

import (
	"github.com/PaloAltoNetworks/pango/util"
	"github.com/PaloAltoNetworks/pango/version"
)

type testCase struct {
	version version.Number
	desc    string
	base    string
	conf    Entry
}

func getTests() []testCase {
	return []testCase{
		{version.Number{7, 0, 0, ""}, "empty rule", util.PreRulebase, Entry{
			Name:        "rule1",
			Description: "blah",
		}},
		{version.Number{7, 0, 0, ""}, "basic rule", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslForwardProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{7, 0, 0, ""}, "rule negate source", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			NegateSource:         true,
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSshProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{7, 0, 0, ""}, "rule negate destination", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			NegateDestination:    true,
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslInboundInspection,
			SslCertificate:       "my cert",
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{7, 0, 0, ""}, "rule disabled", util.PreRulebase, Entry{
			Name:                 "rule2",
			Disabled:             true,
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslForwardProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{8, 1, 0, ""}, "empty rule", util.PreRulebase, Entry{
			Name:        "rule1",
			Description: "blah",
		}},
		{version.Number{8, 1, 0, ""}, "basic rule", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslForwardProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{8, 1, 0, ""}, "rule negate source", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			NegateSource:         true,
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSshProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{8, 1, 0, ""}, "rule negate destination", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			NegateDestination:    true,
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslInboundInspection,
			SslCertificate:       "my cert",
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{8, 1, 0, ""}, "rule disabled", util.PreRulebase, Entry{
			Name:                 "rule2",
			Disabled:             true,
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslForwardProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{8, 1, 0, ""}, "rule with logfwd", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslForwardProxy,
			DecryptionProfile:    "decryption profile",
			ForwardingProfile:    "forwarding profile",
		}},
		{version.Number{9, 0, 0, ""}, "empty rule", util.PreRulebase, Entry{
			Name:        "rule1",
			Uuid:        "uuid123",
			GroupTag:    "tag123",
			Description: "blah",
		}},
		{version.Number{9, 0, 0, ""}, "basic rule", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslForwardProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{9, 0, 0, ""}, "rule negate source", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			NegateSource:         true,
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSshProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{9, 0, 0, ""}, "rule negate destination", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			NegateDestination:    true,
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslInboundInspection,
			SslCertificate:       "my cert",
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{9, 0, 0, ""}, "rule disabled", util.PreRulebase, Entry{
			Name:                 "rule2",
			Disabled:             true,
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslForwardProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{9, 0, 0, ""}, "rule with logfwd", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslForwardProxy,
			DecryptionProfile:    "decryption profile",
			ForwardingProfile:    "forwarding profile",
		}},
		{version.Number{10, 0, 0, ""}, "empty rule", util.PreRulebase, Entry{
			Name:        "rule1",
			Uuid:        "uuid123",
			GroupTag:    "tag123",
			Description: "blah",
		}},
		{version.Number{10, 0, 0, ""}, "basic rule", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslForwardProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{10, 0, 0, ""}, "rule negate source", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			NegateSource:         true,
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSshProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{10, 0, 0, ""}, "rule negate destination", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			NegateDestination:    true,
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslInboundInspection,
			SslCertificate:       "my cert",
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{10, 0, 0, ""}, "rule disabled", util.PreRulebase, Entry{
			Name:                 "rule2",
			Disabled:             true,
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslForwardProxy,
			DecryptionProfile:    "decryption profile",
		}},
		{version.Number{10, 0, 0, ""}, "rule with logfwd", util.PreRulebase, Entry{
			Name:                 "rule2",
			Description:          "blah",
			SourceZones:          []string{"zone1", "zone2"},
			SourceAddresses:      []string{"addy1", "grp1"},
			SourceUsers:          []string{"user2", "user1"},
			DestinationZones:     []string{"dst1", "dst2"},
			DestinationAddresses: []string{"da3", "da2"},
			Tags:                 []string{"t3", "t2", "t1"},
			Services:             []string{"any"},
			UrlCategories:        []string{"url1", "url2"},
			Action:               ActionNoDecrypt,
			DecryptionType:       DecryptionTypeSslForwardProxy,
			DecryptionProfile:    "decryption profile",
			ForwardingProfile:    "forwarding profile",
		}},
		{version.Number{10, 0, 0, ""}, "rule with source hips and successful tls logging", util.PreRulebase, Entry{
			Name:                       "rule1",
			Uuid:                       "uuid123",
			GroupTag:                   "tag123",
			Description:                "blah",
			SourceHips:                 []string{"src1"},
			LogSuccessfulTlsHandshakes: true,
		}},
		{version.Number{10, 0, 0, ""}, "rule with failed handshakes and log setting", util.PreRulebase, Entry{
			Name:                   "rule1",
			Uuid:                   "uuid123",
			GroupTag:               "tag123",
			Description:            "blah",
			DestinationHips:        []string{"dst2", "dst1"},
			LogFailedTlsHandshakes: true,
			LogSetting:             "my log setting",
		}},
	}
}
